### ISSUE TITLE
The reserved indicator "@" cannot start a plain scalar; you need to quote the scalar at line 9 (near "form: @/plugins/raviraj/rjsliders/models/slider/fields.yaml").

### ISSUE THREAD

**Issue by LukeTowers** [rjchauhan/RJSlider-for-OctoberCMS#15]
The config_form.yaml and config_list.yaml for the sliders controller are using an incorrect syntax to refer to the path to the fields.yaml and columns.yaml files for the stable release of OctoberCMS.

The current values are:
config_form.yaml: @/plugins/raviraj/rjsliders/models/slider/fields.yaml
config_list.yaml: @/plugins/raviraj/rjsliders/models/slider/columns.yaml

The correct values are:
config_form.yaml: $/raviraj/rjsliders/models/slider/fields.yaml
config_list.yaml: $/raviraj/rjsliders/models/slider/columns.yaml

**Comment by rjchauhan** [comment]
fixed
