### ISSUE TITLE
Unable to find configuration file plugins/raviraj/raviraj/rjsliders/models/slider/columns.yaml

### ISSUE THREAD

**Issue by zoltiecodes** [rjchauhan/RJSlider-for-OctoberCMS#17]
After I installed the plugin, I got this error:

```

Unable to find configuration file /var/www/octobercms.dev/plugins/raviraj/raviraj/rjsliders/models/slider/columns.yaml defined for Backend\Behaviors\ListController.
/var/www/octobercms.dev/modules/system/traits/ConfigMaker.php line 63
```

As I can see, the plugin name is duplicated in the path, but I don't know why.

**Comment by stopak** [comment]
Unfortunately I have the same issue. Did you find the solution?

**Comment by zoltiecodes** [comment]
Not yet.

**Comment by mitulgolakiya** [comment]
@stopak @teoni you can find fix here: https://github.com/rjchauhan/RJSlider-for-OctoberCMS/pull/18

**Comment by mnishihan** [comment]
@rjchauhan Can you please re-upload the plugin in OctoberCMS plugin repository with the fix for this issue. Otherwise, this plugin is simply un-usable for those, who installs plugins using the Plugin Installer from OctoberCMS backend.

**Comment by gbaumeister** [comment]
+1 Is this project dead? The plugin still hasn't been updated in OctoberCMS Marketplace!

**Comment by rjchauhan** [comment]
Plugin updated on OctoberCMS
