### ISSUE TITLE
Saving a page and then re-opening the advanced component config shows blank fields

### ISSUE THREAD

**Issue by lkhrs** [rjchauhan/RJSlider-for-OctoberCMS#8]
Whenever I configure the advanced component on a page and then save the page, I get an odd issue when I open the advanced config modal again: all the fields are blank.

And then I can't exit the modal because I get a popup saying that "component aliases are required...etc." and I have to reload the page. After I've reloaded the page I can open the modal and see the data I entered.

Really annoying bug. Will be happy to provide more info.

**Comment by rjchauhan** [comment]
try updating octobercms to latest build.
